import { ThemeProvider } from "@/components/shadcn-ui/theme-provider"
import { Inter } from 'next/font/google'
import './global.css'
import AvatarUse from "@/components/shadcn-ui/AvatarUse"
import { ModeToggle } from "@/components/shadcn-ui/ModeToggle"
import DropDown from "@/components/shadcn-ui/DropDown"
import Headerr from "@/components/newui/head"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={inter.className}>

        <ThemeProvider
              // attribute="class"
              // defaultTheme="dark"
              // enableSystem
              // disableTransitionOnChange
            >

        <header
          className="block"
          // style={{ position: 'relative', top:0, bottom: 0, left: 0, right: 0 }}
        >
            <Headerr/>
            <span className="flex justify-end"> 
              <ModeToggle />
            </span>
            
                {/* <AvatarUse/> */}
              {/* <DropDown display={"Navigation"} label={"Select a page"} items={"Home"}/> */}
          </header>   
    
            {children} 
        </ThemeProvider>
          
        </body>
    </html>
  )
}
